[tool.poetry]
name = "bilibili-api-python"
version = "15.5.1.b0"
description = "The fork of module bilibili-api. 哔哩哔哩的各种 API 调用便捷整合（视频、动态、直播等），另外附加一些常用的功能。"
authors = ["Nemo2011 <yimoxia@outlook.com>"]
license = "GPLv3+"
readme = "README.md"
packages = [{include = "bilibili_api_python"}]
include = [
    "bilibili_api/data/**/*.*",
    "bilibili_api/py.typed",
    "README.md", 
    "bilibili_api/data/*.*",
    "bilibili_api/data/article/*.*",
    "bilibili_api/data/geetest/*.*",
    "bilibili_api/data/corerespond/*.*",
]
repository = "https://github.com/Nemo2011/bilibili-api"
homepage = "https://github.com/Nemo2011/bilibili-api"
documentation = "https://nemo2011.github.io/bilibili-api"
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Natural Language :: Chinese (Simplified)",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]


[tool.poetry.dependencies]
python = "^3.8"
urllib3 = "^2.0.3"
aiohttp = "^3.8.4"
beautifulsoup4 = "^4.12.2"
colorama = "^0.4.6"
lxml = "^4.9.3"
pyyaml = "^6.0"
brotli = "^1.0.9"
httpx = "^0.24.1"
qrcode = "^7.4.2"
requests = "^2.31.0"
APScheduler = "^3.10.1"
rsa = "^4.9"
pillow = "^10.0.0"
tqdm = "^4.65.0"
yarl = "^1.9.2"
pycryptodomex = "^3.18.0"
qrcode_terminal = "^0.8"

[tool.black]
line-length = 88
target-version = ["py38", "py39", "py310", "py311"]

[tool.isort]
profile = "black"
line_length = 88
length_sort = true
skip_gitignore = true
force_sort_within_sections = true
src_paths = ["bilibili_api", "tests", "scripts"]

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pytest = "^7.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
